# Generated by Django 5.1.1 on 2024-09-15 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdminModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
                ('city', models.CharField(max_length=30)),
                ('contact', models.IntegerField()),
                ('pasword', models.IntegerField()),
            ],
        ),
    ]
